module.exports = {
  save: 'Save',
  update: 'Update',
  change: 'Change',
  edit: 'Edit',
  add: 'Add',
  addPost: 'Add post',
  publish: 'Publish',
  close: 'Close',
  comment: 'Comment',
  reply: 'Reply',
  setNewPhoto: 'Set new photo',
  crop: 'Crop',
  remove: 'Remove',

  removeFriend: 'Remove friend',
  ban: 'Ban',
  unban: 'Unban',
  banned: 'Banned',
  friend: 'Friend',
  subscriber: 'Subscriber',
  acceptFriend: 'Accept friend',
  sendMail: 'Send mail',

  signIn: 'Sign in',
  signUp: ' Sign up',
  forgotPassword: 'Forgot password?',
  reset: 'Reset',
  attach: 'Attach',
};
